# Generated by Django 2.2.1 on 2019-05-15 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_importance', models.CharField(choices=[('N', 'NA'), ('T', 'To do'), ('I', 'Important'), ('U', 'Urgent')], default='N', max_length=1)),
                ('task_category', models.CharField(choices=[('D', 'Daily Task'), ('C', 'Career'), ('E', 'Educational'), ('F', 'Financial'), ('H', 'Health'), ('M', 'Family Members'), ('P', 'Personal'), ('R', 'Relationship'), ('S', 'Spiritual')], default='D', max_length=1)),
                ('task_title', models.CharField(max_length=200)),
                ('task_summary', models.TextField()),
                ('task_date', models.DateTimeField(default=datetime.datetime(2019, 5, 16, 0, 8, 35, 922657), verbose_name='Date Added')),
                ('task_target', models.DateTimeField(default=datetime.datetime(2019, 5, 16, 0, 8, 35, 922657), verbose_name='Target Date')),
                ('task_acheived', models.DateTimeField(default=datetime.datetime(2019, 5, 16, 0, 8, 35, 922657), verbose_name='Date Acheived')),
            ],
        ),
    ]
