# Generated by Django 2.2.1 on 2019-05-15 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_acheived',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 0, 9, 52, 367206), verbose_name='Date Acheived'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 0, 9, 52, 367206), verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_target',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 0, 9, 52, 367206), verbose_name='Target Date'),
        ),
    ]
