# Generated by Django 2.2.1 on 2019-05-15 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20190516_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_acheived',
            field=models.DateField(verbose_name='Date Acheived'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 0, 57, 44, 27532), verbose_name='Added or Updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_target',
            field=models.DateField(verbose_name='Target Date'),
        ),
    ]
