# Generated by Django 2.2.1 on 2019-05-15 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20190516_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 15, 17, 14, 10, 254973, tzinfo=utc), verbose_name='Added or Updated'),
        ),
    ]
