# Generated by Django 2.2.1 on 2019-05-15 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_auto_20190516_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 1, 31, 52, 10288), verbose_name='Added or Updated'),
        ),
    ]
