# Generated by Django 2.2.1 on 2019-05-15 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_auto_20190516_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_pic',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('D', 'Daily Task'), ('C', 'Career'), ('E', 'Educational'), ('F', 'Financial'), ('H', 'Health'), ('M', 'Family Members'), ('P', 'Personal'), ('R', 'Relationship'), ('S', 'Spiritual')], default='D', max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 15, 20, 11, 52, 809971, tzinfo=utc), verbose_name='Added or Updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_importance',
            field=models.CharField(choices=[('N', 'NA'), ('T', 'To do'), ('I', 'Important'), ('U', 'Urgent')], default='N', max_length=1, verbose_name='Level of Importance'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_summary',
            field=models.TextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
