# Generated by Django 2.2.1 on 2019-05-17 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_auto_20190516_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 9, 52, 16, 100774, tzinfo=utc), verbose_name='Added or Updated'),
        ),
    ]
