# Generated by Django 2.2.1 on 2019-05-17 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_auto_20190517_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_acheived',
            field=models.DateField(blank=True, null=True, verbose_name='Date Acheived'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 11, 0, 30, 708496, tzinfo=utc), verbose_name='Added or Updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_pic',
            field=models.FileField(blank=True, null=True, upload_to='task/media/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_target',
            field=models.DateField(blank=True, null=True, verbose_name='Target Date'),
        ),
    ]
