# Generated by Django 2.2.1 on 2019-05-19 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_auto_20190517_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 11, 15, 46, 352601, tzinfo=utc), verbose_name='Added or Updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_summary',
            field=tinymce.models.HTMLField(),
        ),
    ]
