# Generated by Django 2.2.1 on 2019-05-19 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0009_auto_20190519_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 13, 5, 37, 323557, tzinfo=utc), verbose_name='Added or Updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_pic',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
